### ISSUE TITLE
Location of stock ticker logos

### ISSUE THREAD

**Issue by tyowell-r7** [robbydyer/sports#170]
I am struggling to find the location of the stock ticker logo images. The logs just mention that they are not found but I cannot figure out the exact directory it is looking for when it runs.

05:05PM	error	failed to draw logo for stock	{"error": "open assets/logos/^GSPC.PNG: file does not exist", "symbol": "^GSPC"}
05:05PM	error	failed to draw logo for stock	{"error": "open assets/logos/^IXIC.PNG: file does not exist", "symbol": "^IXIC"}
05:05PM	error	failed to draw logo for stock	{"error": "open assets/logos/^DJI.PNG: file does not exist", "symbol": "^DJI"}
05:05PM	error	failed to draw logo for stock	{"error": "open assets/logos/GME.PNG: file does not exist", "symbol": "GME"}

**Comment by robbydyer** [comment]
The logos are here https://github.com/robbydyer/sports/tree/master/pkg/stockboard/assets/logos . You won't be able to see them on your pi, as they are bundled within the `sportsmatrix` binary at build time. If you'd like, you're welcome to contribute any stock logos as a pull request. I think the ones currently there are just the S&P500 or something.

**Comment by tyowell-r7** [comment]
roger that
