### ISSUE TITLE
Stock ticker start & end timing incorrect

### ISSUE THREAD

**Issue by callyb123** [robbydyer/sports#177]
The Stock ticker begin time is incorrectly starting and ending at 09:30am & 4:00pm rather than 08:00am & 4:30pm.

08:06AM info    outside trading hours, not expiring cache       {"begin": "09:30AM", "end": "04:00PM", "current": "08:06AM"}

**Comment by robbydyer** [comment]
This is fixed in release: https://github.com/robbydyer/sports/releases/tag/v0.0.74
