### ISSUE TITLE
Issue when attempting to upgrade

### ISSUE THREAD

**Issue by tracerrx** [robbydyer/sports#192]
I get the following: 

`curl https://raw.githubusercontent.com/robbydyer/sports/master/script/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   462  100   462    0     0   1346      0 --:--:-- --:--:-- --:--:--  1350
++ uname -m
+ ARCH=armv7l
+ latesturl=https://api.github.com/repos/robbydyer/sports/releases/latest
++ mktemp -d /tmp/sportsinstall.XXXX
+ tmp=/tmp/sportsinstall.AcUa
+ trap 'rm -rf /tmp/sportsinstall.AcUa' EXIT
+ cd /tmp/sportsinstall.AcUa
+ curl -s https://api.github.com/repos/robbydyer/sports/releases/latest
+ grep browser_download_url
+ tr -d '"'
+ grep deb
+ cut -d: -f2,3
+ wget -qi -
bash: line 14: 17771 Exit 23                 curl -s "${latesturl}"
     17772 Segmentation fault      | grep browser_download_url
     17773 Segmentation fault      | grep deb
     17774 Done                    | cut -d: -f2,3
     17775 Done                    | tr -d \"
     17776 Done                    | wget -qi -
+ rm -rf /tmp/sportsinstall.AcUa`

**Comment by robbydyer** [comment]
Was this an upgrade on a Pi with an existing install, or the first time installing? What kind of Pi are you using and what OS?

**Comment by tracerrx** [comment]
Sorry should have closed this... On a pi, apparently an borked apt-get update broke grep...
