### ISSUE TITLE
assumption that chains only affect columns is a bad due to U-mapper property. 

### ISSUE THREAD

**Issue by joermartin** [robbydyer/sports#200]
https://github.com/robbydyer/sports/blob/b7fc232e9b8fd7e037df4f2f00ac6b2dc82d747d/pkg/rgbmatrix-rpi/matrix.go#L139

I use the following RGB-matrix params for my panel: --led-gpio-mapping=adafruit-hat-pwm --led-rows=32 --led-cols=64 --led-multiplexing=1 --led-chain=2 --led-brightness=60 --led-pixel-mapper="U-mapper" --led-show-refresh --led-slowdown-gpio=4

I have two 64(w)x 32(h) panels, stack on top of each other to give me a total 64x64.  They are chained but also use the U-mapper to wrap the extra pixels around to underneath.  more info on U-mapper -> https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/examples-api-use#remapping-coordinates

**Comment by robbydyer** [comment]
Working on a fix here. I have no way to test this with real hardware, so we'll see how it goes for you once I release it.

**Comment by robbydyer** [comment]
Release https://github.com/robbydyer/sports/releases/tag/v0.0.79 has the fix. Give it a try and let me know
