### ISSUE TITLE
Sticky Board Enhancement Idea

### ISSUE THREAD

**Issue by Danrarbc** [robbydyer/sports#242]
I actually really like the sticky feature but sometimes I wish other boards could still be seen, just less often.

Adding something like a stickyDelay option in the config file could enable you to still track your sticky game(s) while still allowing you a look at the rest of the information you have set up.  This could be a per-board option, the default would remain what it now with the permanent display (I guess that'd be a value of 0).  But with this option we'd be able to set, for example, NBA up for a 60 second sticky, MLB with 30 seconds and NHL with just a slightly longer than usual 15 seconds - while still being able to see the other scores and boards we have configured.

**Comment by robbydyer** [comment]
There weren't any live games on for me to test this with, so I just did a beta release. Give it a try and let me know how it goes. https://github.com/robbydyer/sports/releases/tag/v0.0.87beta1

Beta Install:
```
curl https://raw.githubusercontent.com/robbydyer/sports/master/script/beta-install.sh | sudo bash
```

The new config option is a per-sport `stickyDelay`, like https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L200

**Comment by Danrarbc** [comment]
I haven't tried adding more than one team to my active list yet but the feature is working great with one active MLB game in my watch list right now.

**Comment by Danrarbc** [comment]
Decided to test a second live game. It sticks on both for the desired interval and then continues the rotation. Only tested with MLB so far but it seems to work exactly as expected. Does an empty value or 0 still result in a hold until the game is over?

**Comment by robbydyer** [comment]
Awesome, thanks for testing it out.
