### ISSUE TITLE
Add font size config for Stocks + Weather Board

### ISSUE THREAD

**Issue by tracerrx** [robbydyer/sports#317]
on 128x64 size boards, certain font sizes do not display properly.  Using the timeFont config works great to fix the issue.  Is it possible to add the same font config to the weather and stock boards?

**Comment by robbydyer** [comment]
Sorry for the delay. This will rollout with v0.0.107

Here are the new config options to weather and stock font sizes:
https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L1475-L1480
https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L1405-L1410
