### ISSUE TITLE
Stocks

### ISSUE THREAD

**Issue by R1zzler** [robbydyer/sports#332]
What's the best way to add stock tickers? I noticed there aren't any options of how to add other than thru the strings. I saw Yahoo Finance offers API but if you had a sting I could just change the ticket to that would be great!

**Comment by robbydyer** [comment]
You modify the list of tickers in the `symbols:` list in the `stocksConfig` section of the config file: https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L1212
