### ISSUE TITLE
--date-str parameter is broken

### ISSUE THREAD

**Issue by Squigilum** [robbydyer/sports#455]
Running the scoreboard with the --date-str parameter specifying a day in the past no longer works - it shows the current day's scores instead.

It looks like it was broken by the commit 'Setting for previous/advance schedule days.  Restoring the setting of the TodayFunc for the different boards in setTodayFunc() fixed it.

**Comment by robbydyer** [comment]
Fixed in https://github.com/robbydyer/sports/releases/tag/v0.0.104
