### ISSUE TITLE
board not showing current day after advance / previous day update (NHL and NBA)

### ISSUE THREAD

**Issue by opaulhus** [robbydyer/sports#475]
lI'm still having this issue with the dates. I tried commenting out the lines for the advance and previous days, but each morning the board for NHL and NBA doesn't seem to advance ro current day unless I restart the service.

**Comment by robbydyer** [comment]
Yeah, I've noticed this too. I'll look into it as soon as I can.

**Comment by robbydyer** [comment]
I've made a beta release to test the fix. Going to have some folks test it and give feedback before I release it in a regular release.

To install the latest beta: `curl https://raw.githubusercontent.com/robbydyer/sports/master/script/beta-install.sh | sudo bash`

**Comment by robbydyer** [comment]
Fixed in https://github.com/robbydyer/sports/releases/tag/v0.0.109
