### ISSUE TITLE
Use of --led-rgb-sequence

### ISSUE THREAD

**Issue by twfarley** [robbydyer/sports#54]
My matrix requires the use of --led-rgb-sequence as an argument since the colors are flipped. Is there a place I can insert that?

**Comment by robbydyer** [comment]
This option wasn't exposed yet- I just made a change that hopefully makes it work. Once I build/release this change, you would need to set your sequence config under the `hardwardConfig` section of your config file, at the same indentation as `rows` and `cols`.

**Comment by robbydyer** [comment]
I just released v0.0.28 with the fix for this- let me know if it works for you.

**Comment by twfarley** [comment]
Perfect! Thanks so much!
