### ISSUE TITLE
Change font size Live MLB Game

### ISSUE THREAD

**Issue by tracerrx** [robbydyer/sports#570]
Can we get an option in the config to set the font size for scores on the Live MLB Game screen?  I have a 128x64 screen and the scores are tiny during live games.  The current config setting only effects final score screens.

**Comment by tracerrx** [comment]
![IMG_0395 copy](https://user-images.githubusercontent.com/5452178/232947879-b39d6d6c-8005-4a0f-9a9f-55503b93f48e.png)

**Comment by robbydyer** [comment]
Latest release adds this feature. https://github.com/robbydyer/sports/releases/tag/v0.0.114 New `liveViewFont` settings for MLB https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L478
