### ISSUE TITLE
MLS not showing 'Final' when match has ended

### ISSUE THREAD

**Issue by mikertr** [robbydyer/sports#644]
Hi Robby,

I noticed that MLS matches, when they end, still reflect the last minute of play (example:  2 90' + 4') instead of 'FINAL', as other sports do when the event concludes.  I understand this may be a limitation of the consumed API, but want to call it to your attention just in case.  

I LOVE the work you've done and hope to be able to offer monetary support soon.  Cheers!

**Comment by robbydyer** [comment]
Premium version 1.0.22 fixes this https://github.com/robbydyer/rgb-led-matrix-sports-premium/releases/tag/v1.0.22
