### ISSUE TITLE
MLB - Pirates

### ISSUE THREAD

**Issue by skhull2** [robbydyer/sports#894]
When showing games and game result, the Pittsburgh Pirates logo appears to be missing.  It shows the score but there isn't a logo for them on the matrix.

**Comment by robbydyer** [comment]
Fixing with https://github.com/robbydyer/sports/pull/899

**Comment by robbydyer** [comment]
Fixed in the latest release

**Comment by skhull2** [comment]
the fixed logos look awesome!  thanks for fixing them!  Love the scoreboard, my friends are jealous :-)

**Comment by robbydyer** [comment]
Thanks, glad you like it. Check out the premium version too, it's got some cool features. You can do a 7 day trial of it with Patreon https://github.com/robbydyer/rgb-led-matrix-sports-premium
