### ISSUE TITLE
Wanting to help out

### ISSUE THREAD

**Issue by mattcoker** [robbydyer/sports#90]
Hey, this project is awesome. My GoLang experience is pretty minimal, but I would love to help out in any way I can. The NCAAF functionality that you seem to be working on right now is particularly useful to me. Are there any ways I can help out on this repo?

**Comment by robbydyer** [comment]
Hey, I actually just released NCAAF functionality yesterday. The only bits left to work on for that are getting rankings (in progress) and conferences (for configuring "watchTeams" and "favoriteTeams").

Join the Discord channel (https://discord.gg/UUkr4DvG), there's some folks in there that help coming up with new ideas.

**Comment by mattcoker** [comment]
Excellent, thanks for the rapid response! I'll join shortly

**Comment by mattcoker** [comment]
Seems I closed this issue too quickly. The link you provided (which is the same as in the readme) is no longer valid. Is there another link you could provide?

<img width="1392" alt="Screen Shot 2021-07-30 at 10 37 37 AM" src="https://user-images.githubusercontent.com/2382745/127677192-80f540e0-d5d3-45ba-aa65-76eae120a234.png">

**Comment by robbydyer** [comment]
https://discord.gg/8vPp4xfdtV

**Comment by mattcoker** [comment]
Thanks!
